{"version":3,"sources":["../../src/utils/tryDo_.js"],"sourcesContent":["import exitWithError from \"../utils/exitWithError\";\n\nconst tryDo_ = async (app, action) => {    \n    try {\n        await action();\n    } catch (error) {\n        exitWithError(app, error.message || error);\n    }\n};\n\nexport default tryDo_;"],"names":["tryDo_","app","action","error","exitWithError","message"],"mappings":";;;;+BAUA;;;eAAA;;;sEAV0B;;;;;;AAE1B,MAAMA,SAAS,OAAOC,KAAKC,SAAW;IAClC,IAAI;QACA,MAAMA;IACV,EAAE,OAAOC,OAAO;QACZC,IAAAA,sBAAa,EAACH,KAAKE,MAAME,OAAO,IAAIF;IACxC;AACJ;MAEA,WAAeH"}